### ISSUE TITLE
Elements documentation

### ISSUE THREAD

**Issue by gvoskuilen** [sstsimulator/sst-docs#2]
Migrate Elements documentation from sst-simulator.org to this repository and update.

**Comment by berquist** [comment]
Probably related, but all the "Elements" buttons point to http://sst-simulator.org/sst-docs/docs/elements/ember/QuickStart, probably because nothing else has been added yet.  (I was looking for the latest element maturity page that isn't http://sst-simulator.org/SSTPages/SSTDeveloperElementSummaryInfo/ and couldn't remember if it's been done yet.)

**Comment by berquist** [comment]
The docs should also distinguish which elements are in production (present in `make dist` output for a release).

**Comment by gvoskuilen** [comment]
Basic documentation has been released on this site, next up is removing the old docs from the other site.

**Comment by gvoskuilen** [comment]
Complete, closing.
